
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Favicon from "../../public/header-banner.avif"
const roboto = Roboto({weight : "400",subsets : ["latin"]});
import  HeaderBanner  from "../../public/header-banner.avif";
import MenuBar from "./UI-Templates/MenuBar";
import Image from "next/image";
import { useState } from "react";
import Nav from "./UI-Templates/Nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <title>ShoeBrand</title>
          <meta charSet="utf-8" />
          <meta  name="description" content="Build Your Website" />
          <link  rel="icon" sizes="70x70" href={Favicon.src} />
      </head>
      <body className={roboto.className}>
        <header>
            <div className="HeaderShoeDiv">
                <Image
                  src={HeaderBanner}
                  alt="ShoeImage"
                  className="HeaderShoe"
                
                />
            </div>
            <section className="HeaderDescriptionDiv">
                <h1>Regain your confidence on the court.</h1>
                <p>A shoe built with purpose and to take your game to the next level</p>    
            </section> 

            <div id="MovingArrow">
                
            </div>

        </header>
        <Nav/>
       
        {children}
        <footer>
              <small>	&#169;Guru Mahendrakar</small>
        </footer>
      </body>
    </html>
  );
}
